### PR TITLE
Don't set OnSpinWaitInst to SB if VM_Version does not support it

### LINKED ISSUE #16: AL2 AArch64 kernel 4.14 does not support HWCAP_SB
When we run java on Graviton 4 with AL2 kernel 4.14, it fails with:
```
OnSpinWaitInst is SB but current CPU does not support SB instruction
```

This happens because AArch64 kernel 4.14 does not support HWCAP_SB. The corresponding bit is always set to 0.

### PR DESCRIPTION
**Pull request by eastig**
This is a fix of https://github.com/corretto/corretto-25/issues/16

### CODE REVIEW

File: src/hotspot/cpu/aarch64/vm_version_aarch64.cpp [hunk 1]
```diff
@@ -223,7 +223,7 @@ void VM_Version::initialize() {
     }
 
     if (FLAG_IS_DEFAULT(OnSpinWaitInst)) {
-      if (model_is(0xd4f)) {
+      if (model_is(0xd4f) && VM_Version::supports_sb()) {
```
Comment (chadrako) [inline src/hotspot/cpu/aarch64/vm_version_aarch64.cpp:226]: Does this fix the issue? `VM_Version::supports_sb()` performs checks based on the CPU whereas the issue seems to be because of the OS

Comment (eastig) [reply src/hotspot/cpu/aarch64/vm_version_aarch64.cpp:226]: Yes, it does.
`VM_Version::supports_sb()` checks whether `Abstract_VM_Version::_features` has `CPU_sb` bit set.
`Abstract_VM_Version::_features` is initialized in `VM_Version::get_os_cpu_info()` of `src/hotspot/os_cpu/linux_aarch64/vm_version_linux_aarch64.cpp`. In `VM_Version::get_os_cpu_info()` we use Linux API `getauxval(AT_HWCAP)` to get hardware supported features.
So `VM_Version::supports_sb()` performs checks based on the OS.

**Review by chadrako — APPROVED** [review]
